name: Release
on:
  workflow_run:
    workflows: ["Quality Assurance"]
    branches: [main]
    types:
      - completed
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out git
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: kleinanzeigen-ad-swatter.zip
          path: kleinanzeigen-ad-swatter.zip
